### ISSUE TITLE
API is crashed

### ISSUE THREAD

**Issue by SaurabhKhade** [Jaagrav/CodeX-API#13]
I written a program in C++ for infinite memory usage which is as follows

```cpp
#include<iostream>
using namespace std;

int main() {
    while(true) {
        int *n = new int[10000];
    }
}
```

I think the API has been crashed after executing above code as it is showing 'Network Error' now (earlier it was working fine). please try to resolve this issue and place a limit on memory usage and execution time.

**Comment by Jaagrav** [comment]
The API is back live, check out this release. The API should not crash, if it does, it will self recover so it was not your fault, it was just heroku discontinuing their free tier.

https://github.com/Jaagrav/CodeX-API/releases/tag/v1-alpha
