### ISSUE TITLE
Deploy in another platform

### ISSUE THREAD

**Issue by surjendu104** [Jaagrav/CodeX-API#16]
As from 28th Nov 2022 Heroku going to charge money for free dynos ,so I am saying you to host it another platform to get free api hosting service. Thank you!!

**Comment by Jaagrav** [comment]
@surjendu104 

The API is back live, check out this release

https://github.com/Jaagrav/CodeX-API/releases/tag/v1-alpha

**Comment by surjendu104** [comment]
Yeah thanks
