### ISSUE TITLE
Heroku Issue

### ISSUE THREAD

**Issue by GunjanRajTiwari** [Jaagrav/CodeX-API#21]
As Heroku has closed its free tiers the API is down. Please host it on sites like railway or porter so that the API can be up again. Thank you for the amazing API.

**Comment by arpit-mathur-132001** [comment]
You can also deploy on render. I have been using that since Heroku went paid. Thanks for amazing work.

**Comment by Jaagrav** [comment]
The thing is I just tried to get heroku's paid plans but it keeps declining my debit/credit cards, I do not understand why, anyway I will be shifting to digital ocean as soon as I get some time to work on this.

**Comment by Jaagrav** [comment]
@arpit-mathur-132001 @GunjanRajTiwari 

The API is back live, check out this release

https://github.com/Jaagrav/CodeX-API/releases/tag/v1-alpha
