### ISSUE TITLE
[Enhancement] Repetitive Code to Run/Execute Each Language

### ISSUE THREAD

**Issue by YasserDbeis** [Jaagrav/CodeX-API#3]
Creating this as an issue to be tackled in a future PR.

Just noticed that the code to run/execute each language is basically the same, minus the spawn command. Thought the code could be refactored to avoid such redudancy.

I will likely pick this issue up if someone does not already in the upcoming day(s).

**Comment by Jaagrav** [comment]
Have made the required changes, thanks for shining light on this @YasserDbeis.

https://github.com/Jaagrav/CodeX-API/releases/tag/v1-alpha
