### ISSUE TITLE
Bug: API is now suspended.

### ISSUE THREAD

**Issue by BanDroid** [Jaagrav/CodeX-API#33]
Will you keep the api online or you have stopped the services?

**Comment by Jaagrav** [comment]
Hey currently I am out of office, the services would be back by 7th April, 2023.

**Comment by BanDroid** [comment]
> Hey currently I am out of office, the services would be back by 7th April, 2023.

Thank you for the news, i'm glad the project still continues, btw i'm using your api as a plugin for Acode Editor, which now the plugin has 3K download. I hope that would be a great point for CodeX.

**Comment by Jaagrav** [comment]
Sounds awesome, can't let 3k users down, the API is back now, have just made the payments from my phone thanks to the awesome internet connection here in Darjeeling.
