### ISSUE TITLE
Issue with API

### ISSUE THREAD

**Issue by sleepy-jelly** [Jaagrav/CodeX-API#38]
API having issue right now

POST is not working

![image](https://github.com/Jaagrav/CodeX-API/assets/57306207/4c51137e-aa38-4520-bc40-ac128f5c73de)
```
{
    "timeStamp": 1688111559630,
    "status": 500,
    "errno": -2,
    "syscall": "open",
    "code": "ENOENT",
    "path": "/app/codes/ae816f83-a965-42bf-8378-732ad5ddda98.java"
}


```

get is working well

i remember the last time.
same issue started before actually shutting down all functions.

![image](https://github.com/Jaagrav/CodeX-API/assets/57306207/78080a7d-9d9e-4013-9843-3719b37d0311)

**Comment by BanDroid** [comment]
the api surely is down again, i made a plugin for acode editor, it is using codex-api and has been downloaded by 7K users, hopefully the service would online again.

![Screenshot_20230703-195442](https://github.com/Jaagrav/CodeX-API/assets/68449470/cafc2754-eadf-45ff-a36e-89599b8ec8ed)

**Comment by Jaagrav** [comment]
The API is now back online, please check and let me know if it's working.

**Comment by sleepy-jelly** [comment]
> 

it is working nowww
