### ISSUE TITLE
API now suspend..

### ISSUE THREAD

**Issue by sleepy-jelly** [Jaagrav/CodeX-API#43]
![image](https://github.com/Jaagrav/CodeX-API/assets/57306207/33e60130-bd6f-498a-aa9a-3081beab5052)
GET, POST both of methods are same to me

**Comment by sleepy-jelly** [comment]
Fri, 11 Aug 2023 05:48:21 GMT tested 
same status.

**Comment by Jaagrav** [comment]
https://github.com/Jaagrav/CodeX-API/issues/46#issuecomment-1703860135
