### ISSUE TITLE
API is not working.

### ISSUE THREAD

**Issue by Sunilrai486** [Jaagrav/CodeX-API#53]
Request failed with status code 503

**Comment by connorholm** [comment]
I am getting this same error...does anyone know what happened?

**Comment by itsabishiek** [comment]
Bro,` https://api.codex.jaagrav.in/.` The API seems to be suspended and still we are not getting any support, smh..

**Comment by Sunilrai486** [comment]
@Jaagrav Any idea about this issue?

**Comment by Jaagrav** [comment]
Done fixed, check now. I don't know why render.com does not auto-credit the invoice from me. Constantly need to add my credit card again and again.
