### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by ishaanxgupta** [Jaagrav/CodeX-API#61]
https://api.codex.jaagrav.in/

This API is down please get it up again it was very useful
Showing 500 error

**Comment by PranshuLakhotia** [comment]
https://api.codex.jaagrav.in/
API is not working currently

**Comment by Jaagrav** [comment]
Kar raha hu start bhai log pata nahi kaise fatt gaya

**Comment by Jaagrav** [comment]
Fixed, Choreo added Trivy vulnerability scan for some reason, where the scan started failing due to vulnerabilities so I did the smart thing and turned the scanner off!
